# src/scripts/repo_features/report.py
"""Render one pass as markdown (#291).

The prose matters as much as the table. A list of what the big repositories
ship reads as a leaderboard unless the page says otherwise, and it is not one
— it is a record of what is *served*, which `DP-005` says is not a record of
what is good. `unbound-lineage.md` is the model: say what a row usually means
where the reader will hit it, not in a decision nobody opens.
"""
# inactive-ok-file: ADR-058 — Proposed, and it is the decision this module
# implements rather than one it relies on.


from __future__ import annotations

STAMP = ("<!-- GENERATED by `python -m src.scripts.repo_features` — "
         "edit the manifest, not this file. -->")

PREAMBLE = """\
A technique is in one of these repositories because somebody shipped it. That
is evidence about **`consensus`** — how far the field has converged — and about
nothing else: not whether the practice is sound, and not this record's own
`status`, which is its editorial position (`ADR-058`, `DP-005`).

Read the columns as different strengths. **Confirmed** means a practice's
title or summary is about the feature. **Candidates** means the phrase appears
only in some practice's body, which is a lead and is wrong most of the time —
`SOTA-143` mentions FP8 once and is a practice about µP. **Absent** means
nothing in the record mentions it at all, and is the column worth working.

A feature that has **gone** since the last run is a prompt to read the
practice again, never a reason to lower its consensus. A library can narrow
its scope without the field changing its mind.

One caveat on that column, because it is invisible otherwise: the lockfile
records what was *extracted*, not what the repository contains. Editing an
extractor or a manifest entry therefore reads exactly like the repository
having changed. Check what moved in the manifest before believing a large
`new`/`gone` on a quiet week.
"""


def render(observed: dict, deltas: dict, matches: dict) -> str:
    """`observed` from `run.observe`, `deltas` from `run.changes`, and
    `matches` mapping repo -> feature -> (confirmed, candidates)."""
    out = ["# What the big repositories implement", "", STAMP, "", PREAMBLE]
    for name in sorted(observed):
        obs, delta = observed[name], deltas.get(name, {})
        out += [f"## {name} — `{obs['repo']}` ({obs['kind']})", "",
                f"Read at `{obs['sha'][:12]}`. {len(obs['items'])} item(s); "
                f"{len(delta.get('new', []))} new, "
                f"{len(delta.get('gone', []))} gone since the last run.", ""]
        if obs["kind"] == "catalogue":
            held = matches.get(name, {})
            missing = [i for i in obs["items"] if not held.get(i)]
            out += [f"**{len(obs['items']) - len(missing)} of "
                    f"{len(obs['items'])} already in the reading list.** The "
                    f"rest are a ranked candidate queue, not a backlog — most "
                    f"of a catalogue is techniques nobody adopted.", "",
                    "Not held: " + (", ".join(f"`{i}`" for i in missing)
                                    or "none."), ""]
            continue
        out += ["| feature | confirmed | candidates |", "|---|---|---|"]
        for item in obs["items"]:
            confirmed, candidates = matches.get(name, {}).get(item, ([], []))
            out.append(f"| {item} | "
                       f"{', '.join(confirmed) if confirmed else '—'} | "
                       f"{len(candidates) or '—'} |")
        absent = [i for i in obs["items"]
                  if not any(matches.get(name, {}).get(i, ([], []))[0])]
        out += ["", f"**{len(absent)} feature(s) with no practice about "
                    f"them.** " + (", ".join(f"`{a}`" for a in absent)
                                   or "None."), ""]
        for label in ("new", "gone"):
            if delta.get(label):
                out += [f"**{label.capitalize()} since the last run:** "
                        + ", ".join(f"`{x}`" for x in delta[label]), ""]
    return "\n".join(out)
