name: Build Registry

on:
  push:
    # paths:
    #   - 'data/research.yaml'
    #   - 'src/scripts/registry/**'
    #   - ./.github/workflows/build_registry.yml
  workflow_dispatch:  # Allow manual triggering
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight

jobs:
  # Add test job from test workflow
  test:
    uses: ./.github/workflows/test.yml
  
  build:
    needs: test  # Make build dependent on tests passing
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[all]"
      
      - name: Build registry
        run: python -m scripts.registry.cli build
