# File: .github/workflows/deploy-frontend.yaml
name: Deploy Frontend

on:
  workflow_dispatch:
  push:
    #branches: [ main ]
    paths:
      - 'web/**'
      - 'data/registry.yaml'
      - '.github/workflows/deploy-frontend.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Copy data file
        run: |
          mkdir -p web/data
          cp data/registry.yaml web/data/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web
          branch: gh-pages
