# .github/workflows/deploy-frontend.yml
name: Deploy Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'data/**'
      - '.github/workflows/deploy-frontend.yaml'
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for getting commit history

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Build site
        working-directory: frontend
        env:
          NEXT_PUBLIC_BASE_PATH: '/anthology-of-the-sota'
        run: npm run build && npm run export
        
      # Add .nojekyll file to bypass Jekyll processing
      - name: Add .nojekyll file
        run: touch frontend/out/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # The branch the action should deploy to
          folder: frontend/out  # The folder the action should deploy
          clean: true  # Automatically remove deleted files from the deployment
