# File: .github/workflows/deploy-frontend.yaml
name: Deploy Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'web/**'
      - 'data/registry.yaml'
      - '.github/workflows/deploy-frontend.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Create the deployment directory with web files and data
      - name: Prepare deployment
        run: |
          mkdir -p deploy
          cp -r web/* deploy/
          mkdir -p deploy/data
          cp data/registry.yaml deploy/data/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deploy
          branch: gh-pages
