# .github/workflows/deploy-frontend.yaml
name: Deploy Frontend

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'data/**'
      - '.github/workflows/deploy-frontend.yaml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Debug file structure
        run: |
          echo "Project root:"
          ls -la
          echo "\nData directory:"
          ls -la data/
          echo "\nRegistry YAML content:"
          cat data/registry.yaml | head -n 20

      # Clean install to avoid any package-lock.json issues
      - name: Clean install
        working-directory: frontend
        run: |
          rm -f package-lock.json
          npm install

      - name: Copy data and verify
        run: |
          mkdir -p frontend/src/data
          cp data/registry.yaml frontend/src/data/
          echo "\nVerifying copied YAML:"
          ls -la frontend/src/data/
          cat frontend/src/data/registry.yaml | head -n 20

      - name: Build site
        working-directory: frontend
        env:
          NEXT_PUBLIC_BASE_PATH: '/anthology-of-the-sota'
          NODE_ENV: 'development'  # Enable error messages
        run: npm run build

      - name: Add .nojekyll file
        run: touch frontend/out/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: frontend/out
          clean: true
