name: Tests

on:
  push:
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/test.yml"
  workflow_dispatch:
  workflow_call:
    
env:
  PYTHON_VERSION: "3.11"

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
      
      - name: Install dependencies
        run: |
          pip install -e ".[all]"
      
      - name: Run tests
        run: |
          pytest tests/ -v
